tab_spaces = 4
max_width = 80
# comment_width = 80 # NIGHTLY-ONLY
# wrap_comments = true # NIGHTLY-ONLY

# group_imports = "StdExternalCrate" # NIGHTLY-ONLY
# imports_granularity = "One" # NIGHTLY-ONLY
reorder_imports = true
reorder_modules = true

merge_derives = true
